export const TOGGLE_BOXED_LAYOUT = 'TOGGLE_BOXED_LAYOUT';
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSED_NAV';
export const TOGGLE_NAV_BEHIND = 'TOGGLE_NAV_BEHIND';
export const TOGGLE_FIXED_HEADER = 'TOGGLE_FIXED_HEADER';
export const CHANGE_SIDEBAR_WIDTH = 'CHANGE_SIDEBAR_WIDTH';
export const CHANGE_COLOR_OPTION = 'CHANGE_COLOR_OPTION';
export const CHANGE_THEME = 'CHANGE_THEME';

export const GET_PLAYER = 'GET_PLAYER';
export const GET_PLAYER_SUCCESS = 'GET_PLAYER_SUCCESS';
export const GET_PLAYER_FAILURE = 'GET_PLAYER_FAILURE';

export const GET_PLAYERS = 'GET_PLAYERS';
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const GET_PLAYERS_FAILURE = 'GET_PLAYERS_FAILURE';

export const GET_ATTRIBUTES = 'GET_ATTRIBUTES';
export const GET_ATTRIBUTES_SUCCESS = 'GET_ATTRIBUTES_SUCCESS';
export const GET_ATTRIBUTES_FAILURE = 'GET_ATTRIBUTES_FAILURE';

export const GET_LISTS = 'GET_LISTS';
export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS';
export const GET_LISTS_FAILURE = 'GET_LISTS_FAILURE';

export const GET_LIST = 'GET_LIST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE';

export const CREATE_LIST = 'CREATE_LIST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILURE = 'CREATE_LIST_FAILURE';

export const SET_ACTIVE_LIST = 'SET_ACTIVE_LIST';
export const SET_ACTIVE_LIST_SUCCESS = 'SET_ACTIVE_LIST_SUCCESS';
export const SET_ACTIVE_LIST_FAILURE = 'SET_ACTIVE_LIST_FAILURE';

export const SET_PLAYER_RANK = 'SET_PLAYER_RANK';
export const SET_PLAYER_RANK_SUCCESS = 'SET_PLAYER_RANK_SUCCESS';
export const SET_PLAYER_RANK_FAILURE = 'SET_PLAYER_RANK_FAILURE';

export const GET_JWT = 'GET_JWT';
export const GET_JWT_SUCCESS = 'GET_JWT_SUCCESS';
export const GET_JWT_FAILURE = 'GET_JWT_FAILURE';

export const SET_JWT_USER = 'SET_JWT_USER';
export const SET_JWT_USER_SUCCESS = 'SET_JWT_USER_SUCCESS';
export const SET_JWT_USER_FAILURE = 'SET_JWT_USER_FAILURE';

export const INVALIDATE_JWT_USER = 'INVALIDATE_JWT_USER';
export const INVALIDATE_JWT_USER_SUCCESS = 'INVALIDATE_JWT_USER_SUCCESS';
export const INVALIDATE_JWT_USER_FAILURE = 'INVALIDATE_JWT_USER_FAILURE';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOAD_MESSAGE = 'LOAD_MESSAGE';
export const LOAD_MESSAGE_SUCCESS = 'LOAD_MESSAGE_SUCCESS';
export const LOAD_MESSAGE_FAILURE = 'LOAD_MESSAGE_FAILURE';

export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';
export const CLOSE_MESSAGE_SUCCESS = 'CLOSE_MESSAGE_SUCCESS';
export const CLOSE_MESSAGE_FAILURE = 'CLOSE_MESSAGE_FAILURE';

export const OPEN_MODAL = 'OPEN_MODAL';
export const OPEN_MODAL_SUCCESS = 'OPEN_MODAL_SUCCESS';
export const OPEN_MODAL_FAILURE = 'OPEN_MODAL_FAILURE';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CLOSE_MODAL_SUCCESS = 'CLOSE_MODAL_SUCCESS';
export const CLOSE_MODAL_FAILURE = 'CLOSE_MODAL_FAILURE';

export const ADD_PLAYERS_TO_LIST = 'ADD_PLAYERS_TO_LIST';
export const ADD_PLAYERS_TO_LIST_SUCCESS = 'ADD_PLAYERS_TO_LIST_SUCCESS';
export const ADD_PLAYERS_TO_LIST_FAILURE = 'ADD_PLAYERS_TO_LIST_FAILURE';
