
const leagueConversionMap = {
  NHL: 'National Hockey League',
  AHL: 'American Hockey League',
  'Kontinental Hockey League': 'Russia',
  ECHL: 'ECHL',
  USHL: 'United States Hockey League',
  WHL: 'Western Hockey League',
  OHL: 'Ontario Hockey League',
  QMJHL: 'Quebec Major Junior Hockey League',
  'Big Ten': 'Central Collegiate Hockey Association',
  NCHC: 'Northern Collegiate Hockey Association',
  WCHA: 'Western Collegiate Hockey Association',
  OJHL: 'Ontario Provincial Junior A Hockey League',
};

const nhlTeams = [
  { short: 'ana', region: 'Anaheim', name: 'Ducks' },
  { short: 'ari', region: 'Arizona', name: 'Coyotes' },
  { short: 'bos', region: 'Boston', name: 'Bruins' },
  { short: 'buf', region: 'Buffalo', name: 'Sabres' },
  { short: 'cgy', region: 'Calgary', name: 'Flames' },
  { short: 'car', region: 'Carolina',  name: 'Hurricanes' },
  { short: 'chi', region: 'Chicago', name: 'Blackhawks' },
  { short: 'col', region: 'Colorado', name: 'Avalanche' },
  { short: 'clb', region: 'Columbus', name: 'Blue Jackets' },
  { short: 'dal', region: 'Dallas', name: 'Stars' },
  { short: 'det', region: 'Detroit', name: 'Redwings' },
  { short: 'edm', region: 'Edmonton', name: 'Oilers' },
  { short: 'fla', region: 'Florida', name: 'Panthers' },
  { short: 'lak', region: 'Los Angeles', name: 'Kings' },
  { short: 'min', region: 'Minnesota', name: 'Wild' },
  { short: 'mtl', region: 'Montreal', name: 'Canadiens' },
  { short: 'nsh', region: 'Nashville', name: 'Predators' },
  { short: 'njd', region: 'New Jersey', name: 'Devils' },
  { short: 'nyi', region: 'New York', name: 'Islanders' },
  { short: 'nyr', region: 'New York', name: 'Rangers' },
  { short: 'ott', region: 'Ottawa', name: 'Senators' },
  { short: 'phi', region: 'Philadelphia', name: 'Flyers' },
  { short: 'pit', region: 'Pittsburgh', name: 'Penguins' },
  { short: 'sjs', region: 'San Jose', name: 'Sharks' },
  { short: 'stl', region: 'St. Louis', name: 'Blues' },
  { short: 'tbl', region: 'Tampa Bay', name: 'Lightning' },
  { short: 'tor', region: 'Toronto', name: 'Maple Leafs' },
  { short: 'van', region: 'Vancouver', name: 'Canucks' },
  { short: 'vgk', region: 'Vegas', name: 'Golden Knights' },
  { short: 'wsh', region: 'Washington', name: 'Capitals' },
  { short: 'wpg', region: 'Winnipeg', name: 'Jets' },
];

const tempGMList = [
  'bstar',
  'Tucker',
  'Eric',
  'Craig',
  'Desquareious',
  'Luke',
  'Obi wan Kenobi',
  'Chris',
  'Ho Borvat',
  'Oshawa-General',
  'Lebas',
  'Osens',
  'Slava',
  'Enorama',
  'EvilWalrus',
  'Goran',
  'Matsoni',
  'Mikey G',
  'Little Liam',
  'Sambergler',
  'Toad',
  'Tate',
  'Will',
  'elrune',
  'Tyler',
  'Glass',
  'dLamb',
  'Jazon',
  'Iqbal',
  'Chace',
];

const grades = ['A+','A','A-','B+','B','B-','C+','C','C-','D+','D','D-','F'];

export { leagueConversionMap, nhlTeams, tempGMList, grades };
